[manager]
show_hidden = true
sort_by = "natural"

[preview]
wrap = "yes"
tab_size = 2

[opener]
edit = [
    { run = 'vim "$@', for = "unix"}, 
    { run = 'vim %*', for "windows"}
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "vidoe/*", use = "play" }
]

[plugin]
preloaders = [
   # PDF
   { mime = "application/pdf", run = "pdf" },
]
previewers = [
   # PDF
   { mime = "application/pdf", run = "pdf" },
]
